- name: install ruby
  hosts: all
  become: true
  tasks:
    - name: install ruby
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - ruby-full
          - ruby-bundler
          - build-essential

